config/routes.rb
Rails.application.routes.draw do

  post "/votar-na-ideia" => 'high_scores#votar', as: :votar_na_ideia

  devise_for :users

  
  root 'pages#index'
  resources :high_scores
  resources :ideas
  resources :classifications

  namespace :admin do
    root 'classifications#index'
    resources :classifications
  end
  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :classification
  belongs_to :user
  
  validates :name, :description, :classification, :user, presence: true
  validates :name, length: {minimum: 3}
  validates :description, length: {minimum: 10, maximum:120}


end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /ideas
  # GET /ideas.json
  def index
     @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = current_user.ideas.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)


    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :classification_id, :user_id)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= Classification.all.size -%>
    <%= f.association :classification, prompt: 'Select one classification' %>
      <div class="field">
        <%= f.input :user_id, as: :hidden,  input_html: {value: current_user.id} %><br>
        <%= f.input :name %><br>
        <!--<%= f.text_field :name %>-->
      </div>
      <div class="field">
        <%= f.input :description, rows: 10 %><br>
        <!--<%= f.text_area :description, rows: 10 %>-->
      </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class="page-header">
  <%= link_to 'New Idea', new_idea_path,class:'btn btn-primary pull-right' %>
  <h1>Listing Ideas</h1>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Classification</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.classification.name %></td>
        <td><%= idea.user.email %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path, class: 'btn btn-primary pull-left' %>

app/views/ideas/show.html.erb
<p>
  <strong>Classification:</strong>
  <%= @idea.classification.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>


<p>
  <strong>User:</strong>
  <%= @idea.user.email %>
</p>

<p>
  <strong>Quantidade de Votos</strong>
  <%= HighScore.where(idea_id: @idea.id).size %>
</p>
<p>
  <strong>Média de Votos</strong>
  <%= HighScore.where(idea_id: @idea.id).average(:vote).to_i %>
</p>
<% if user_signed_in? %>
<fieldset>
	<legend>Votar</legend>
	<%= simple_form_for HighScore.new, url: votar_na_ideia_path do |f| %>
	  <%= f.input_field :user_id, as: :hidden, value: current_user.id %>
	  <%= f.input_field :idea_id, as: :hidden, value: @idea.id %>
	  <%= f.input :vote, as: :radio_buttons, collection: HighScore::NOTAS %>
	  <div class="form-actions">
	    <%= f.submit 'Votar', class: 'btn btn-primary' %>
	  </div>
	<% end %>
</fieldset>

<% end %>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>