config/routes.rb
Rails.application.routes.draw do

  post "/votar-na-ideia" => 'high_scores#votar', as: :votar_na_ideia

  devise_for :users

  
  root 'pages#index'
  resources :high_scores
  resources :ideas
  resources :classifications

  namespace :admin do
    root 'classifications#index'
    resources :classifications
  end
  

end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :ideas
  validates :name, presence: true
  validates :name, length: {minimum: 3}

end

app/controllers/admin/classifications_controller.rb
class Admin::ClassificationsController < AdminController
  before_action :set_admin_classification, only: [:show, :edit, :update, :destroy]

  # GET /admin/classifications
  # GET /admin/classifications.json
  def index
    @classifications = Classification.page(params[:page]).per(10)
  end

  # GET /admin/classifications/1
  # GET /admin/classifications/1.json
  def show
  end

  # GET /admin/classifications/new
  def new
    @classification = Classification.new
  end

  # GET /admin/classifications/1/edit
  def edit
  end

  # POST /admin/classifications
  # POST /admin/classifications.json
  def create
    @classification = Classification.new(admin_classification_params)

    respond_to do |format|
      if @classification.save
        format.html { redirect_to admin_classifications_path, notice: 'Classification was successfully created.' }
        format.json { render :show, status: :created, location: @classification }
      else
        format.html { render :new }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/classifications/1
  # PATCH/PUT /admin/classifications/1.json
  def update
    respond_to do |format|
      if @classification.update(admin_classification_params)
        format.html { redirect_to [:admin, @classification], notice: 'Classification was successfully updated.' }
        format.json { render :show, status: :ok, location: @classification }
      else
        format.html { render :edit }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/classifications/1
  # DELETE /admin/classifications/1.json
  def destroy
    @classification.destroy
    respond_to do |format|
      format.html { redirect_to admin_classifications_url, notice: 'Classification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_classification
      @classification = Classification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_classification_params
      params.require(:classification).permit(:name)
    end
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_action :set_classification, only: [:show, :edit, :update, :destroy]

  # GET /classifications
  # GET /classifications.json
  def index
    @classifications = Classification.order('id ASC').page(params[:page]).per(10)
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
  end

  # GET /classifications/new
  def new
    @classification = Classification.new
  end

  # GET /classifications/1/edit
  def edit
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(classification_params)
    
    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'Classification was successfully created.' }
        format.json { render :show, status: :created, location: @classification }
      else
        format.html { render :new }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifications/1
  # PATCH/PUT /classifications/1.json
  def update
    respond_to do |format|
      if @classification.update(classification_params)
        format.html { redirect_to @classification, notice: 'Classification was successfully updated.' }
        format.json { render :show, status: :ok, location: @classification }
      else
        format.html { render :edit }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification.destroy
    respond_to do |format|
      format.html { redirect_to classifications_url, notice: 'Classification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classification
      @classification = Classification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_params
      params.require(:classification).permit(:name)
    end


end

app/helpers/admin/classifications_helper.rb
module Admin::ClassificationsHelper
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/admin/classifications/_form.html.erb
<%= simple_form_for [:admin, @classification] do |f| %>
  <%= f.input :name %>
  <%= error_span(@classification[:name]) %>
    <%= f.button :submit, :class => 'btn-primary pull-left' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                classifications_path, :class => 'btn btn-default pull-left' %>
<% end %>

app/views/admin/classifications/edit.html.erb
<%- model_class = Classification -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/classifications/index.html.erb
<%- model_class = Classification -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_admin_classification_path, :class => 'btn btn-primary pull-right' %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= paginate @classifications %>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @classifications.each do |classification| %>
      <tr>
        <td><%= link_to classification.id, admin_classification_path(classification) %></td>
        <td><%= classification.name %></td>
        <td><%=l classification.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_classification_path(classification), :class => 'btn btn-default btn-xs pull-left' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_classification_path(classification),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger pull-left' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @classifications %>

app/views/admin/classifications/new.html.erb
<%- model_class = Classification -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/classifications/show.html.erb
<%- model_class = Classification -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @classification.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_classifications_path, :class => 'btn btn-default pull-right'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
             edit_admin_classification_path(@classification), :class => 'btn btn-default pull-right' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_classification_path(@classification),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger pull-right' %>