config/routes.rb
Rails.application.routes.draw do

  post "/votar-na-ideia" => 'high_scores#votar', as: :votar_na_ideia

  devise_for :users

  
  root 'pages#index'
  resources :high_scores
  resources :ideas
  resources :classifications

  namespace :admin do
    root 'classifications#index'
    resources :classifications
  end
  

end

app/views/layouts/_admin_header_site.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Admin</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Main Page', admin_root_path %></li>
        <li><%= link_to 'Classification', admin_classifications_path %></li>
        <li class="time-now"><a href="javascript:;"><%= l(time_now, format: :basic) -%></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="icon fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="icon fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="icon fa fa-github"></i></a></li>
        <li><a href=""><%= current_user.email -%></a> </li>
        <li>
          <%= link_to destroy_user_session_path, :method => Devise.sign_out_via do %>
              <i class="fa fa-power-off"></i> Sair
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_header_site.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Factory Idea</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Main Page', root_path %></li>
        <li><%= link_to 'Classification', classifications_path %></li>
        <li><%= link_to 'Ideas', ideas_path %></li>
        <li class="time-now"><a href="javascript:;"><%= l(time_now, format: :basic) -%></a></li>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="icon fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="icon fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="icon fa fa-github"></i></a></li>
    <% unless user_signed_in? -%>
        <li><a href="/admin"><i class="icon fa fa-lock"></i></a></li>
    <% else -%>
        <li><a href="/admin"><i class="icon fa fa-lock"></i></a></li>
        <li>
            <%= link_to destroy_user_session_path, :method => Devise.sign_out_via do %>
              <i class="icon fa fa-power-off"></i>
            <% end %>
        </li>
    <% end -%>        
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<section class="header-cam">
  <div class="container">
    <div class="col-md-1 logo-cam">
      <a href="#" title="Factory Idea">
        <%= image_tag 'logo.png', height: "100", width: "89", alt: "" %>
      </a>
    </div>
    <div class="col-md-5 cam-name">
      <h2>Factory Idea 2015.1</h2>
      <p>+Ideas</p>
    </div>
    <div class="col-md-6">
      <div class="input-group search-cam hidden-xs">
        <form action="" method="GET" class="form-inline form-search-cam">
          <div class="form-group">
            <input type="text" name="s" class="form-control placeholder" placeholder="Perquisar">
          </div>
                        <span class="input-group bnt-cam-search">
                            <button class="btn btn-default" type="submit"><span class="glyphicon cam-icon-search glyphicon-search" aria-hidden="true"></span></button>
                        </span>
        </form>
      </div><!-- /input-group -->
    </div>
  </div>
</section>

app/views/layouts/_sidebar_site.html.erb
<!-- Blog Sidebar -->
<div class="col-md-3 sidebar">

  <!-- Blog Categroias -->
  <div class="well">
    <h4>Classifications</h4>
    <div class="row">
      <div class="col-lg-4">
        <ul class="list-unstyled">
      <% Classification.all.each do |classification| %>

          <li>
            <%= link_to classification.name, '#' -%>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="pt-Br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Admin * FactoryIdea" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


  </head>
  <body>

  <%= render 'layouts/admin_header_site'  -%>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="US">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "FactoryIdea" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


</head>
<body>

<%= render 'layouts/header_site' -%>


<!-- Page Content -->
<div class="container">

  <div class="row">
    <%= bootstrap_flash %>
    <%= yield %>

<%= render 'layouts/sidebar_site' unless %[classifications ideas devise/sessions devise/registrations].include?(controller_name) -%>

  </div>
  <!-- /.row -->

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>&copy; Curso Ruby on Rails 2015</p>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </footer>

</div>
<!-- /.container -->

<%= debug params %>

<%= javascript_include_tag "application" %>
</body>

</html>